/**
 * Global test setup for Vitest
 * Mocks all external service clients to prevent real API calls during testing
 */

import { vi } from 'vitest'

// ============================================================================
// Mock Apify Client
// ============================================================================

export const mockApifyClient = {
  actor: vi.fn(() => ({
    call: vi.fn().mockResolvedValue({ defaultDatasetId: 'mock-dataset-id' }),
  })),
  dataset: vi.fn(() => ({
    listItems: vi.fn().mockResolvedValue({
      items: [
        {
          title: 'Test Video Title',
          description: 'Test video description for testing purposes',
          viewCount: 1000,
          subtitles: 'This is a test transcript with sample content for testing.',
          channelName: 'Test Channel',
          publishedAt: '2024-01-15T10:00:00Z',
        },
      ],
    }),
  })),
}

vi.mock('apify-client', () => {
  class MockApifyClient {
    constructor() {}
    actor() {
      return mockApifyClient.actor()
    }
    dataset() {
      return mockApifyClient.dataset()
    }
  }

  return {
    ApifyClient: MockApifyClient,
  }
})

// ============================================================================
// Mock Anthropic SDK
// ============================================================================

export const mockAnthropicClient = {
  messages: {
    create: vi.fn().mockResolvedValue({
      content: [
        {
          type: 'text',
          text: `# Complete Guide to Test Subject (Sample Headline)

**Meta Description:** Learn about test subject with this comprehensive guide covering key concepts, best practices, and advanced techniques for successful implementation.

## Introduction

This is a sample article generated for testing purposes. It demonstrates the structure and format of articles generated by the SEO content transformer.

## Getting Started

To begin working with the test subject, you'll need to understand the fundamental concepts and set up your environment properly. This section provides essential background information.

## Core Concepts

Understanding the core principles is crucial for success. These concepts form the foundation of everything you'll learn in this guide.

## Best Practices

Following established best practices ensures your implementation is robust, maintainable, and performs well in production environments.

## Advanced Techniques

Once you've mastered the basics, these advanced techniques will help you tackle complex scenarios and optimize your workflow.

## Common Pitfalls

Learn about common mistakes and how to avoid them. This knowledge will save you time and prevent frustration during development.

## FAQ

**Q: What is the main benefit of this approach?**
A: The main benefit is improved efficiency and better results through structured methodology and proven techniques.

**Q: How long does it take to learn?**
A: Most people can grasp the basics in a few hours, but mastery takes practice and real-world application over weeks or months.

**Q: What are the prerequisites?**
A: Basic understanding of related concepts is helpful, but this guide is designed to be accessible to beginners with minimal prior knowledge.

**Q: Can this be used in production?**
A: Yes, the techniques described here are production-ready and used by many successful organizations worldwide.

**Q: Where can I find more resources?**
A: Additional resources, documentation, and community support are available through official channels and online communities.`,
        },
      ],
      usage: {
        input_tokens: 1000,
        output_tokens: 2000,
      },
    }),
  },
}

vi.mock('@anthropic-ai/sdk', () => {
  return {
    default: class MockAnthropic {
      messages = mockAnthropicClient.messages
    },
  }
})

// ============================================================================
// Mock Supabase Client
// ============================================================================

export const mockSupabaseClient = {
  from: vi.fn(() => ({
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    single: vi.fn().mockResolvedValue({
      data: {
        id: 'mock-id',
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
      },
      error: null
    }),
  })),
  auth: {
    getUser: vi.fn().mockResolvedValue({
      data: {
        user: {
          id: 'mock-user-id',
          email: 'test@example.com',
        }
      },
      error: null
    }),
  },
}

vi.mock('@supabase/supabase-js', () => ({
  createClient: vi.fn(() => mockSupabaseClient),
}))

// ============================================================================
// Mock QStash Client
// ============================================================================

export const mockQStashClient = {
  publishJSON: vi.fn().mockResolvedValue({
    messageId: 'mock-qstash-message-id',
    url: 'https://qstash.upstash.io/v1/publish/mock',
  }),
}

vi.mock('@upstash/qstash', () => ({
  Client: vi.fn(() => mockQStashClient),
}))

// ============================================================================
// Mock Resend Client
// ============================================================================

export const mockResendClient = {
  emails: {
    send: vi.fn().mockResolvedValue({
      id: 'mock-resend-email-id',
      from: 'noreply@test.com',
      to: 'user@example.com',
      created_at: '2024-01-15T10:00:00Z',
    }),
  },
}

vi.mock('resend', () => ({
  Resend: vi.fn(() => mockResendClient),
}))

// ============================================================================
// Global Test Environment Setup
// ============================================================================

// Set up environment variables for testing
process.env.APIFY_API_TOKEN = 'mock-apify-token'
process.env.ANTHROPIC_API_KEY = 'mock-anthropic-key'
process.env.NEXT_PUBLIC_SUPABASE_URL = 'https://mock-supabase.supabase.co'
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY = 'mock-supabase-anon-key'
process.env.QSTASH_TOKEN = 'mock-qstash-token'
process.env.RESEND_API_KEY = 'mock-resend-key'
