-- Add scraped_data and article_data columns to generation_queue
-- These store intermediate data from the scraping and transformation pipeline

ALTER TABLE public.generation_queue
  ADD COLUMN scraped_data JSONB,
  ADD COLUMN article_data JSONB;

-- Update status check constraint to include new statuses
ALTER TABLE public.generation_queue
  DROP CONSTRAINT IF EXISTS generation_queue_status_check;

ALTER TABLE public.generation_queue
  ADD CONSTRAINT generation_queue_status_check
    CHECK (status IN ('pending', 'processing', 'scraped', 'transforming', 'transformed', 'publishing', 'published', 'failed'));

-- Add index for JSONB columns for faster queries
CREATE INDEX idx_generation_queue_scraped_data ON public.generation_queue USING GIN (scraped_data);
CREATE INDEX idx_generation_queue_article_data ON public.generation_queue USING GIN (article_data);

-- Comment for documentation
COMMENT ON COLUMN public.generation_queue.scraped_data IS 'YouTube video metadata and transcript from Apify scraper';
COMMENT ON COLUMN public.generation_queue.article_data IS 'SEO-optimized article generated by Claude transformer';
